baseurl = "https://yonimelman.github.io/"
languageCode = "en-us"
Title = "hudev"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"

theme = "pickles"
[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  github = "yonimelman"
  linkedin = "yoni-melman-2b5a5aa1"
  disqus = "yonimelman"

  # Disqus shortname
  # Google Analytics API key.
  ga_api_key = "Your Google Analytics tracking id"
  author = "Yoni Melman"
  avatar = "https://avatars3.githubusercontent.com/u/5171942?s=460&v=4"
  contact = "mailto:yoni.melman@gmail.com"
  bio = "Python Developer, Food and Markup languges enthusiast."

  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "# Blog for human developers"
  # Logo image. This is displayed ogp image.
  favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 2

#[[menu.main]]
#    name = "About"
#    url = "/about"
#    weight = 3

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
